backend:
  name: git-gateway
  branch: feature/actualizacionContenido

media_folder: "docs/public/uploads"
public_folder: "/public/uploads"

collections:
  - name: "base_de_datos_noticias"
    label: "Gestor de Noticias"
    files:
      - label: "Todas las Noticias"
        name: "archivo_noticias"
        file: "docs/content/noticias.json"
        fields:
          - label: "Publicaciones"
            name: "posts"
            widget: "list"
            fields:
              - {label: "Nombre del Autor", name: "author", widget: "string", default: "Administración CCX"}
              - {label: "Foto del Autor (Opcional)", name: "avatar", widget: "image", required: false}
              - {label: "Fecha", name: "date", widget: "datetime"}
              - {label: "Foto de la Noticia", name: "image", widget: "image", required: false}
              - {label: "Texto de la Noticia", name: "body", widget: "text"}